language: node_js
node_js:
  - "stable"
before_install:
  - gem install sass
  - gem install compass
  - npm install -g grunt-cli
  - npm install -g bower
install: npm install
before_script: 
  - bower install
script: grunt build
